line-length = 160
indent-width = 4
target-version = "py311"

[lint]
select = ["E4", "E7", "E9", "F"]
ignore = ["F403", "F405"]

[format]
quote-style = "single"
indent-style = "space"
#skip-magic-trailing-comma = false
line-ending = "auto"
docstring-code-format = false
